version: '3.8'

services:
  bank-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bank-container
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000